# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      - uses: azure/docker-login@v1
        with:
          login-server: mcwworkshop.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # - name: Login to ACR
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.IMAGES_TOKEN }}
      # - run: |
      #     docker build . -t contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
      #     docker push contoso.azurecr.io/nodejssampleapp:${{ github.sha }} 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: tailspintoys/web:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: push Image
        run: docker push mcwworkshop.azurecr.io/tailspintoys/web:latest
      
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, ${{ github.workspace }}  

      # - name: Build solution
      #   run: dotnet build
      #   working-directory: ${{ github.workspace }}/src/TailspinToysWeb
      

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
